export const toeic500: string[][] = [
  ["flight", "proposal", "invitation", "lease", "teach"],
  ["landscape", "appreciate", "complaint", "condition", "award"],
  ["renovation", "colleague", "contemporary", "necessary", "once"],
  ["area", "greet", "crew", "gain", "multiple"],
  ["attach", "sorry", "refund", "difficult", "seminar"],
  ["change", "effort", "estimate", "ship", "member"],
  ["team", "upcoming", "film", "shuttle", "wait"],
  ["strategy", "although", "remember", "problem", "reservation"],
  ["receive", "interview", "despite", "program", "way"],
  ["center", "special", "understand", "wear", "competition"],
  ["carry", "term", "show", "manual", "appliance"],
  ["complimentary", "different", "reschedule", "buy", "traffic"],
  ["highly", "hard", "opportunity", "response", "repair"],
  ["pay", "neither", "currently", "training", "a lot of"],
  ["lobby", "convenient", "status", "floor", "reception"],
  ["personnel", "issue", "fabric", "management", "corporate"],
  ["discount", "distribute", "attention", "surprise", "technique"],
  ["provide", "applicant", "delay", "effective", "cancel"],
  ["spend", "both", "free", "exhibition", "schedule"],
  ["sincerely", "manage", "secure", "through", "beverage"],
  ["important", "professor", "contain", "postpone", "guest"],
  ["solution", "résumé", "vacation", "learn", "each"],
  ["advise", "excuse me.", "furniture", "signature", "discuss"],
  ["permit", "merchandise", "device", "remove", "document"],
  ["architect", "director", "suitable", "register", "assist"],
  ["people", "type", "class", "news", "branch"],
  ["except", "fee", "correct", "mayor", "attract"],
  ["fix", "initiative", "ability", "attend", "vehicle"],
  ["leave", "convention", "due", "museum", "attempt"],
  ["decision", "again", "analysis", "arrange", "plan"],
  ["quality", "inquire", "delighted", "professional", "sound"],
  ["consultant", "welcome", "continue", "artwork", "title"],
  ["base", "department", "transfer", "budget", "purpose"],
  ["committee", "read", "rather", "payment", "candidate"],
  ["immediately", "paperwork", "mind", "performance", "acknowledge"],
  ["without", "revenue", "few", "bill", "nearly"],
  ["luggage", "anyway", "bring", "per", "venue"],
  ["include", "avoid", "replace", "update", "either"],
  ["soon", "remind", "while", "experience", "badge"],
  ["ensure", "appear", "service", "figure", "environment"],
  ["comfortable", "piece", "usual", "speech", "passenger"],
  ["idea", "campaign", "under", "choose", "choice"],
  ["let's", "deadline", "previous", "increase", "behind"],
  ["meeting", "together", "search", "visit", "laboratory"],
  ["distance", "course", "else", "better", "public"],
  ["conduct", "display", "agenda", "library", "produce"],
  ["procedure", "certainly", "board", "receipt", "shop"],
  ["design", "fact", "charge", "notify", "renew"],
  ["intend", "install", "check", "view", "collect"],
  ["delivery", "clear", "close", "write", "participate in"],
  ["item", "unfortunately", "congratulations", "hire", "allow"],
  ["launch", "local", "resource", "specific", "employee"],
  ["variety", "however", "council", "building", "according to"],
  ["supervisor", "commercial", "sell", "excellent", "arrive"],
  ["associate", "quantity", "exercise", "example", "conference"],
  ["require", "early", "facility", "available", "consider"],
  ["warranty", "place", "key", "total", "standard"],
  ["potential", "during", "involve", "return", "consumer"],
  ["handle", "trouble", "investment", "into", "prefer"],
  ["coworker", "feature", "research", "seek", "win"],
  ["open", "wish", "famous", "think", "after"],
  ["therefore", "vendor", "encourage", "negotiate", "executive"],
  ["instead", "inventory", "talk", "expect", "specialize in"],
  ["extend", "home", "describe", "industrial", "since"],
  ["admission", "presentation", "though", "quite", "representative"],
  ["project", "prepare", "whether", "inspection", "submit"],
  ["forget", "size", "financial", "large", "reduce"],
  ["catering", "additional", "payroll", "subject", "nearby"],
  ["tier", "purchase", "especially", "hold", "responsible"],
  ["recruit", "great", "properly", "position", "seem"],
  ["book", "further", "annual", "raise", "successful"],
  ["mistake", "coupon", "specialist", "participant", "expire"],
  ["ingredient", "supply", "medical", "finish", "exchange"],
  ["topic", "often", "invoice", "concern", "damage"],
  ["deposit", "assign", "ticket", "meet", "request"],
  ["benefit", "task", "expo", "brochure", "process"],
  ["cause", "exceed", "industry", "until", "application"],
  ["expand", "begin", "accommodate", "location", "price"],
  ["far from", "impress", "cost", "between", "actually"],
  ["honor", "material", "recently", "similar", "feedback"],
  ["favorite", "customer", "complete", "client", "move"],
  ["probably", "travel", "vote", "suggestion", "excite"],
  ["identification", "ideal", "confirm", "realize", "recognize"],
  ["tour", "reliable", "before", "logo", "construction"],
  ["set", "improve", "review", "find", "dining"],
  ["ready", "save", "conversation", "throughout", "patient"],
  ["maintenance", "busy", "equipment", "park", "demonstration"],
  ["already", "remain", "belong", "inform", "worry"],
  ["possible", "verify", "sign", "recommend", "expensive"],
  ["interior", "various", "mainly", "advance", "entrance"],
  ["several", "grocery", "promote", "send", "approve"],
  ["contact", "survey", "traditional", "agree", "protection"],
  ["official", "head", "report", "always", "last"],
  ["note that", "be interested in", "revise", "fine", "temporary"],
  ["replacement", "publish", "region", "appointment"],
];
