export const toeic700: string[][] = [
  ["truly", "aisle", "scholarship", "scope", "talent"],
  ["principle", "overview", "inventory", "recreation", "conduct"],
  ["prospect", "domestic", "beforehand", "novice", "insight"],
  ["feasible", "procedure", "vacant", "accurate", "crucial"],
  ["perceive", "interruption", "likewise", "failure", "downstairs"],
  ["competence", "incline", "reject", "cardboard", "allocate"],
  ["reply", "welfare", "tolerate", "discard", "warrant"],
  ["incredible", "landlord", "voice", "zealous", "calculate"],
  ["behavior", "sensitive", "auditorium", "skip", "comprehensive"],
  ["translate", "vendor", "utensil", "massive", "suspicion"],
  ["prohibit", "reluctant", "relief", "discontinue", "annex"],
  ["moderate", "enormous", "transcript", "commend", "cite"],
  ["uniformity", "appliance", "capability", "inconvenience", "thus"],
  ["embarrassing", "adjacent to", "gradually", "cuisine", "spokesperson"],
  ["justify", "prototype", "fluctuate", "typical", "overcome"],
  ["deserve", "represent", "fiscal", "tend to do", "agenda"],
  ["scheme", "origin", "prerequisite", "pedestrian", "eventually"],
  ["reference", "background", "standstill", "consecutive", "pursue"],
  ["complicated", "timepiece", "sustain", "proficiency", "awful"],
  ["turbulent", "empty", "reimburse", "aspect", "outdated"],
  ["durable", "beside", "generous", "concept", "unanimous"],
  ["cooperation", "lottery", "import", "quote", "appropriately"],
  ["eliminate", "fieldwork", "fortunate", "engagement", "browse"],
  ["checklist", "facilitate", "thaw", "exclusive", "property"],
  ["innovative", "urgency", "encounter", "situation", "brochure"],
  ["withstand", "archive", "postal", "illustrate", "premise"],
  ["pottery", "outcome", "valid", "admit", "invaluable"],
  ["enthusiastic", "useful", "token", "usage", "dramatic"],
  ["wilderness", "municipal", "bargain", "remark", "warehouse"],
  ["turnout", "amazing", "rapid", "superb", "stroll"],
  ["respectively", "amateur", "zeal", "tariff", "expire"],
  ["absence", "spectator", "readability", "controversial", "foreign"],
  ["oval", "majority", "hallway", "intermediate", "heritage"],
  ["coincidence", "handout", "intensive", "maintain", "precise"],
  ["asset", "subsidiary", "candidate", "neutral", "checkup"],
  ["anymore", "examine", "whereas", "refreshment", "declare"],
  ["swiftly", "tuition", "minimum", "devote", "nevertheless"],
  ["function", "reinforce", "confident", "instant", "supplement"],
  ["retrieve", "genre", "moreover", "overflow", "shortage"],
  ["component", "reward", "utilize", "installment", "occupy"],
  ["milestone", "slate", "shopper", "acquisition", "population"],
  ["resign", "vice", "furthermore", "refill", "average"],
  ["expertise", "conclude", "surrounding", "guidebook", "extinguish"],
  ["unearth", "excessive", "obliged", "hesitate", "deficit"],
  ["persuade", "malfunction", "enlarge", "reasonable", "enhance"],
  ["designate", "wheelbarrow", "superintendent", "warning", "plumber"],
  ["duration", "explanation", "vacancy", "mission", "fantastic"],
  ["detour", "opposite", "transparent", "eligible", "generate"],
  ["enterprise", "speculate", "regardless of", "reputation", "sightseeing"],
  ["utility", "seldom", "expedite", "utilization", "factor"],
  ["demand", "mere", "remote", "flaw", "recall"],
  ["sufficient", "struggle", "biography", "conform", "forecast"],
  ["income", "kickoff", "destination", "venue", "entertainment"],
  ["curb", "accustom", "zenith", "validate", "substitute"],
  ["worldwide", "infrastructure", "imagine", "transfer", "manuscript"],
  ["meanwhile", "fundamental", "perhaps", "surpass", "freelance"],
  ["prevent", "execute", "keynote", "souvenir", "workforce"],
  ["vaporize", "approximately", "virtue", "bid"],
];
