export const toeic600: string[][] = [
  ["profile", "actually", "envelope", "voucher", "apologize"],
  ["digest", "compliment", "reflect", "entire", "practical"],
  ["representative", "perfect", "inside", "administrative", "miss"],
  ["predict", "otherwise", "newly", "quarter", "itinerary"],
  ["layout", "expertise", "aware", "in the meantime", "foundation"],
  ["above", "sponsorship", "stack", "involve", "cafeteria"],
  ["delay", "regulation", "monitor", "administration", "encourage"],
  ["luck", "provide", "remove", "depart", "include"],
  ["clearance", "exit", "general", "budget", "further"],
  ["patron", "willing", "responsible", "baggage", "affordable"],
  ["a couple of", "feature", "current", "broadcast", "enclose"],
  ["cuisine", "compare", "annual", "volume", "overseas"],
  ["decorate", "method", "conference", "explore", "directory"],
  ["proud", "fare", "format", "applicant", "fund"],
  ["publicity", "finalize", "in writing", "executive", "consumer"],
  ["urgent", "anniversary", "classic", "whenever", "college"],
  ["retire", "internship", "pleasure", "quick", "implement"],
  ["approximate", "offer", "assess", "guarantee", "oversee"],
  ["delighted", "steady", "appear", "moment", "recipient"],
  ["prescription", "restore", "institute", "exactly", "below"],
  ["luggage", "neighborhood", "architect", "progress", "definitely"],
  ["reservation", "recommend", "aside from", "primary", "fee"],
  ["blueprint", "notice", "structure", "entry", "hardly"],
  ["transaction", "severe", "automatically", "invest", "worth"],
  ["formal", "shortly", "flexible", "invoice", "frequent"],
  ["knowledge", "proceed", "evidence", "exclusive", "discover"],
  ["i'm afraid…", "evaluation", "attend", "exceed", "numerous"],
  ["approach", "donate", "earn", "colleague", "improve"],
  ["regularly", "projector", "ceiling", "decrease", "tenant"],
  ["promote", "on behalf of", "plenty", "conservation", "invite"],
  ["advance", "efficiency", "major", "result", "particular"],
  ["benefit", "prosperous", "wheelbarrow", "occur", "expert"],
  ["acquire", "from scratch", "shipment", "initial", "input"],
  ["common", "hurry", "unique", "waterproof", "broad"],
  ["photocopy", "fail", "secretary", "analyst", "accomplishment"],
  ["deal with", "satisfaction", "incorporate", "decide", "instantly"],
  ["adjust", "preservation", "cashier", "checkout", "individual"],
  ["handle", "networking", "enroll", "in a row", "medication"],
  ["department", "survey", "accommodate", "dental", "district"],
  ["auditorium", "instrument", "valuable", "introduction", "unless"],
  ["develop", "owe", "passenger", "shortage", "transportation"],
  ["constant", "eatery", "summary", "handout", "figure"],
  ["priority", "review", "explain", "alone", "walkway"],
  ["emphasize", "estate", "highlight", "designate", "advertising"],
  ["previous", "simple", "language", "decade", "guess"],
  ["influence", "showcase", "finally", "questionnaire", "dedicate"],
  ["beyond", "replacement", "normally", "equally", "expose"],
  ["refund", "temperature", "appropriate", "decline", "whole"],
  ["clerk", "absolutely", "accounting", "workplace", "workshop"],
  ["direct", "huge", "concern", "subscribe", "uniform"],
  ["clarify", "metro", "identification", "anticipate", "prior to"],
  ["certificate", "qualify", "social", "panel", "be supposed to"],
  ["profit", "overhead", "handbook", "compact", "promise"],
  ["overnight", "significant", "defect", "degree", "society"],
  ["outstanding", "except", "expect", "facility", "eligible"],
  ["exhibit", "judge", "demand", "audience", "participate"],
  ["appreciate", "relevant", "familiar", "afford", "contribute"],
  ["maximum", "autograph", "advantage", "undergo", "connect"],
  ["terminal", "establish", "onto", "nutrition", "merger"],
  ["accessible", "plenty of", "complicated", "manufacture", "achievement"],
  ["cater", "insurance", "gather", "attract", "store"],
  ["delicious", "satisfy", "yield", "durable", "remind"],
  ["additional", "ladder", "inquire", "eliminate", "determine"],
  ["means", "impact", "contract"],
];
